- name: Install desktop environment and terminal 
  become: true
  apt:
    name:
      - alacritty
      - tmux
      - fzf
      - i3
      - i3blocks
      - rofi
      - picom
      - feh
      - fonts-jetbrains-mono
  tags:
    - install
    - work-environment

- name: Install starship
  become: true
  shell: |
    curl -sS https://starship.rs/install.sh > install.sh && sh ./install.sh -y && rm ./install.sh
  tags:
    - install
    - work-environment

